### ISSUE TITLE
Hang after login

### ISSUE THREAD

**Issue by ekoeryanto** [netlify/netlify-cms#1231]
**- Do you want to request a *feature* or report a *bug*?**
- bug

**- What is the current behavior?**
- hang after successfully logged in, need to refresh 2-3 times to get redirected to admin area
![image](https://user-images.githubusercontent.com/36023898/38383979-204b8040-3938-11e8-8155-3cf28570f6d3.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
- redirect to admin area after successfully logged in

**- Please mention your CMS, node.js, and operating system version.**

CMS: 1.4.0
Node: 8.11.0

**- Please link or paste your `config.yml` below if applicable.**
https://github.com/pakeweb/apek/blob/master/static/admin/config.yml

**Comment by erquhart** [comment]
Hmm I believe the `netlify-identity-widget.js` script in use should handle this.

@bcomnes know anything?

**Comment by erquhart** [comment]
As @tech4him1 mentioned, this may be addressed by #1251. Will release soon.

**Comment by erquhart** [comment]
@ekoeryanto can you test this and see if it's resolved in 1.6.0?

**Comment by ekoeryanto** [comment]
OK I'll try

**Comment by ekoeryanto** [comment]
Fixed

**Comment by erquhart** [comment]
Awesome, thanks for retesting!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by galvarez421** [comment]
I am still experiencing this issue, using netlify-cms 1.9.3. I only need to refresh once and then the admin interface appears, but it seems that it will never appear unless I refresh after the login confirmation modal appears.

**Comment by ekoeryanto** [comment]
@galvarez421 check the netlify identity widget setup and also try to clear the localstorage with `localStorage.clear()`

**Comment by Undistraction** [comment]
I'm seeing the same issue with v3.0.0-rc.1. 

Login succeeds but doesn't forward to the admin page. You need to manually navigate or refresh the page.

I've added the following logging to your suggested code:

<script>
    if (window.netlifyIdentity) {
      window.netlifyIdentity.on("init", user => {
        console.log('NETLIFY INIT')
        if (!user) {
          window.netlifyIdentity.on("login", () => {
            console.log('NETLIFY LOGIN')
            document.location.href = "/admin/";
          });
        }
      });
    }
  </script>

On production neither callback is fired.

**Comment by tech4him1** [comment]
@Undistraction That seems to be an unrelated problem, can you please file a new issue?

**Comment by ekoeryanto** [comment]
@Undistraction  v3.0.0-rc.1 of what?

**Comment by erquhart** [comment]
He's referring to the Gatsby Netlify CMS plugin.

@Undistraction I just got a fix for this merged, get yourself the latest release and it should be good.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ekoeryanto** [comment]
Ah, I see, sorry.

@erquhart about gatsbyjs/gatsby#7857 should we discuss it here, in this repo?

**Comment by Undistraction** [comment]
@erquhart Thanks. That has solved the problem locally, but there is a redirect happening when deployed to Netlify. If I navigate to `example.netlify.com/admin/` it redirects to `example.netlify.com/admin/admin/?no-cache=1` and loads the default wrapper page, meaning the script responsible for handling the redirect is no longer present, so no redirect takes place after login. I think this is a completely separate issue, but I'm unsure where to open it - here or in the repo for the Gatsby plugin …

**Comment by erquhart** [comment]
@ekoeryanto yep this repo, just open a separate issue.

@Undistraction got a fix up: https://github.com/gatsbyjs/gatsby/pull/8286
