### ISSUE TITLE
Uploading images with GitLab as backend is broken

### ISSUE THREAD

**Issue by Kavakuo** [netlify/netlify-cms#1565]
**- Do you want to request a *feature* or report a *bug*?**
Bug, see below for the bugfix. Pull request is coming.

**- What is the current behavior?**
Uploading images with GitLab as backend is broken.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Use GitLab as backend and try to upload a new image.

**- What is the expected behavior?**
The image is uploaded and commited by the cms.

**- Bugfix**
Use the `result` function instead of `get` in the `uploadAndCommit` function (see [here](https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-backend-gitlab/src/API.js#L188)). I will create a pull request to fix this issue.

**- Please link or paste your `config.yml` below if applicable.**
```
backend:
  name: gitlab
  branch: master # Branch to update (optional; defaults to master)
  repo: [repository]
  auth_type: implicit # Required for implicit grant
  app_id: [applicationId] # Application ID from your GitLab settings
  api_root: https://gitlab.lan/api/v4
  base_url: https://gitlab.lan
  auth_endpoint: oauth/authorize
```

**Comment by tech4him1** [comment]
Thanks for working on a PR, let us know if you need any help!

**Comment by estherholleman** [comment]
This is still not working for me. It builds fine, but when I try to change or upload an image I still get 'no assets found' even with a fresh install of the official Gatsby starter with GitLab and after updating gatsby-plugin-netlify-cms to version ^1.0.12, gatsby-plugin-netlify to ^1.0.21, and netlify-cms to "^1.9.3 . Is there perhaps anything else I should be updating or something I'm forgetting?

**Comment by tech4him1** [comment]
@estherholleman This fix was released in CMS version 2.0.7, please upgrade and try again.

**Comment by piedoom** [comment]
I am still getting the error on 2.0.8, I will update soon with more details

**Comment by estherholleman** [comment]
I cannot seem to update any version higher than 1.9.3 for netlify cms and 1.0.12 in gatsby-plugin-netlify-cms (in the gatsby-starter-netlify-cms, downloaded today). Whenever I do an npm install, it just downloads those versions again. 

I also attempted to follow the gatsby netlify cms tutorial https://www.gatsbyjs.org/docs/netlify-cms/ , and here I can install the latest versions, however then gatsby develop doesn't work anymore when I add netlify cms to the gatsby hello world starter (following the exact instructions there). I get the error: error There was an error compiling the html.js component for the development server. Error: Module not found: Error: Cannot resolve module 'netlify-cms/dist/cms.css' ,node_modules/netlify-cms/dist/cms.css doesn't exist (directory default file). I have no idea how to get that css file in there, I did install netlify-cms and there is a netlify-cms folder in my node-modules folder.

I also attempted to force the updates by updating the package.json file with the updated version numbers manually, deleting node_modules and running npm install. This does seem to update the modules (to 2.0.1 for the plugin and 2.0.8 for netlify-cms) but then I get the same "Error: Module not found: Error: Cannot resolve module 'netlify-cms/dist/cms.css" error again when trying to run gatsby develop.

**Comment by estherholleman** [comment]
So in my case this was a problem with the gatsby-plugin-netlify-cms not working with any netlify cms version above 2 on gatsby v1, (https://github.com/gatsbyjs/gatsby/issues/6802). I've created a test site in gatsby v2 with netlify cms v2.0.8 and image uploading works there.

**Comment by tech4him1** [comment]
@estherholleman Great, glad you got it working.

@piedoom If you don't mind, can you open a new issue instead of commenting here?

**Comment by piedoom** [comment]
Sure, I will do that in a moment!

**Comment by tech4him1** [comment]
@piedoom Still an issue?

**Comment by DavidRayner** [comment]
I still have this issue with my site which was based off the hugo starter
I will try to reproduce with the hugo starter upgraded to v2.x

![image](https://user-images.githubusercontent.com/9212074/44000758-77b2bcdc-9e1d-11e8-8fdf-6e37ddc0c610.png)

**Comment by DavidRayner** [comment]
I believe this issue still exists on netlify-cms 2.0.9

I made a Netlify site using GitHub and https://github.com/DavidRayner/one-click-hugo-cms. I was able to upload media without any problem.

I made another Netlify site using GitLab and https://gitlab.com/davidrayner/one-click-hugo-cms (an import of my GH repo) - and I was not able to upload media.

**Comment by tech4him1** [comment]
@DavidRayner I can reproduce, looking into it. For some reason, Redux is getting a `MEDIA_LIBRARY_FAILURE`. This line is then undefined:

https://github.com/netlify/netlify-cms/blob/f801b192211b1e1953ced969a3093eab9e04e14d/packages/netlify-cms-core/src/actions/mediaLibrary.js#L84

**Comment by piedoom** [comment]
Thanks for posting more info @DavidRayner - sorry I haven't been at the computer much lately so I was unable to respond with further stuff.  This is the exact behavior i am experiencing as well.

**Comment by tech4him1** [comment]
@piedoom @DavidRayner Great, at least we have a repro case. I've opened a new issue to track this problem, let's move discussion there: https://github.com/netlify/netlify-cms/issues/1608.
