### ISSUE TITLE
Hidden fields don't work when added through a list widget with variable types

### ISSUE THREAD

**Issue by LesterGallagher** [netlify/netlify-cms#2363]
**Describe the bug**

When using the new list widget with variable types, hidden fields don't work. When you add a new item the (nested) hidden fields don't get set to the default value.

**To Reproduce**

```yaml
- label: Items
  name: items
  widget: list
  type: list
  types:
    - label: Item
      name: item
      widget: object
      type: some_type
      fields:
        - label: Name
          name: name
          widget: string
        - label: Subtype
          name: subtype
          widget: hidden
          default: sponsor_item
          required: true
  # more items
```

**Expected behavior**

It should set the default values.

**Applicable Versions:**

 - Netlify CMS app version: 2.9.1

**Comment by erquhart** [comment]
I believe #2374 will address this.

**Comment by LesterGallagher** [comment]
Fixed in #2374

**Comment by barthc** [comment]
@erquhart  @LesterGallagher  #2374 did not fix this issue, sorry. I will send in another PR that will address this issue and #2378

**Comment by erquhart** [comment]
Thanks so much @barthc
